name: Build and test packrat modules

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu
        pip3 install psutil transformers python-interface pandas plotnine pyarrow
    - name: Test with pytest
      run: python -m unittest -v tests/tests_cache.py
